#!/bin/bash

scp config-sshserver sshserver:~/.irssi/config
./bot.theme.sh > bot.theme
scp config-bot default.theme bot.theme sshserver:~/.irssi/

rsync -avL --exclude=.svn scripts/ sshserver:~/.irssi/scripts/
