#!/bin/bash

scp config-{sshserver,bot} sshserver:~/.irssi/config
scp default.theme sshserver:~/.irssi/

./bot.theme.sh > bot.theme
scp bot.theme sshserver:~/.irssi/

rsync -avL --exclude=.svn scripts/ sshserver:~/.irssi/scripts/
