#!/usr/bin/env bash

set -Eeu -o pipefail

determine_here() {
	(
		cd -- "$(dirname -- "$0")"
		pwd -P
	)
}

export KOMPUTILOJ_PATH=$(determine_here)
printf 'Using KOMPUTILOJ_PATH=%q\n' "$KOMPUTILOJ_PATH" >&2
DEFAULT_NIXOS=$(nix-instantiate --eval "$KOMPUTILOJ_PATH" -A default_nixos | egrep -o '[^"]+')
printf 'Using nixpkgs source %q\n' "$DEFAULT_NIXOS" >&2
export NIXPKGS_PATH=$(nix-instantiate --eval "$KOMPUTILOJ_PATH" -A sources."$DEFAULT_NIXOS".nix_path | egrep -o '[^"]+')
printf 'Using nixpkgs path %q\n' "$NIXPKGS_PATH" >&2

printf 'Building komputiloj...\n' >&2
nix-build \
	--show-trace \
	--out-link "$KOMPUTILOJ_PATH"/komputiloj-result \
	-A capsules.komputiloj.packages.komputiloj \
	-- "$KOMPUTILOJ_PATH"
printf 'Running komputiloj...\n' >&2
exec "$KOMPUTILOJ_PATH"/komputiloj-result/bin/komputiloj "$@"

