#!/usr/bin/env bash

set -Eeu -o pipefail

determine_here() {
	(
		cd -- "$(dirname -- "$0")"
		pwd -P
	)
}
export KOMPUTILOJ_PATH=$(determine_here)
printf 'Using KOMPUTILOJ_PATH=%q\n' "$KOMPUTILOJ_PATH" >&2

DEFAULT_NIXOS=nixos_22_05 # the source we use as nixpkgs in nixos-rebuild

do_update_sources() {
	for source_dir in "$KOMPUTILOJ_PATH"/sources.d/*; do
		if [[ -d "$source_dir" ]]; then
		(
			cd -- "$source_dir"
			if [[ -x update ]]; then
				printf 'Updating source %s\n' "$source_dir" >&2
				./update
			else
				printf 'Skipping source without update script: %s\n' "$source_dir" >&2
			fi
		)
		fi
	done
}

do_nixos_rebuild() {
	local nixpkgs_path

	printf 'Using nixpkgs source %q\n' "$DEFAULT_NIXOS" >&2
	nixpkgs_path=$(nix-instantiate --eval "$KOMPUTILOJ_PATH"/sources.nix -A "$DEFAULT_NIXOS".unpacked | egrep -o '[^"]+')
	printf 'Using implicit current host configuration from /etc/nixos\n' >&2 # TODO just use a (host-specific) dir in KOMPUTILOJ_PATH directly
	export NIX_PATH="komputiloj=$KOMPUTILOJ_PATH:nixpkgs=$nixpkgs_path:nixos-config=/etc/nixos/configuration.nix"
	printf 'Using nixos-rebuild from PATH\n' >&2
	exec sudo nixos-rebuild "$@"
}

do_cleanup() {
	local host

	if [[ "$#" -ne 1 ]]; then
		printf 'Usage: %q cleanup HOSTNAME\n' "$0" >&2
		return 1
	fi

	host="$1"
	if [[ "$host" = "$HOSTNAME" ]]; then
		echo "Doing local nix garbage collection..."
		sudo nix-collect-garbage
		echo
		echo "Garbage was collected. However,"
		echo "there might be lingering old system generations:"
		echo
		sudo nix-env -p /nix/var/nix/profiles/system --list-generations
		echo
		echo "To delete:"
		echo "    sudo nix-env -p /nix/var/nix/profiles/system --delete-generations NUMBER..."
		echo "    sudo nix-collect-garbage"
	else
	case "$host" in
		gently)
			# TODO study https://nixos.wiki/wiki/Storage_optimization
			# for an automated solution.
			ssh root@gently.radstand.nl nix-collect-garbage -d
		;;
		*)
			printf "Don't know how to clean up host %q.\n" "$host" >&2
			return 1
		;;
	esac
	fi
}

main() {
	local cmd
	
	if [[ "$#" -eq 0 ]]; then
		printf 'Usage: %q COMMAND\n' "$0" >&2
		exit 1
	fi

	cmd="$1"
	shift
	case "$cmd" in
		update-sources)
			do_update_sources
		;;
		nixos-rebuild)
			do_nixos_rebuild "$@"
		;;
		deploy)
			exec -- "$KOMPUTILOJ_PATH"/serviloj/deploy "$@"
		;;
		nixops)
			exec -- "$KOMPUTILOJ_PATH"/serviloj/command "$@"
		;;
		cleanup)
			do_cleanup "$@"
		;;
		*)
			printf 'Unknown command %q\n' "$cmd" >&2
		;;
	esac
}

main "$@"
