#!/usr/bin/env bash

set -Eeu -o pipefail

if [[ "$#" -ne 1 ]]; then
	echo "Usage: $0 CHANNEL_NAME" >&2
	exit 1
fi

channel="$1"

channel_url=https://channels.nixos.org/"$channel"
current_url=$(curl --head --silent --write-out "%{redirect_url}\n" --output /dev/null "$channel_url")/nixexprs.tar.xz

if [[ -z "$current_url" ]]; then
	echo "Could not determine current url for channel $channel_url" >&2
	echo "Likely cause: a typo in the channel name." >&2
	echo "Less likely cause: a change in nixos.org redirect structure." >&2
	exit 2
fi

current_sha=$(nix-prefetch-url --unpack "$current_url")

printf 'current_url = "%s";\n' "$current_url"
printf 'current_sha = "%s";\n' "$current_sha"

