#!/usr/bin/env bash

set -Eeu -o pipefail

for source_dir in ~/komputiloj/sources.d/*; do
	if [[ -d "$source_dir" ]]; then
	(
		cd -- "$source_dir"
		if [[ -x update ]]; then
			printf "Updating source %s\n" "$source_dir" >&2
			./update
		else
			printf "Skipping source without update script: %s\n" "$source_dir" >&2
		fi
	)
	fi
done

