#!/bin/bash

set -Eeu
set -o pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
	printf 'Usage: %q DEVICE [DIRNAME]\n' "$0" >&2
	exit 1
fi

DEVICE="$1"

if [[ $DEVICE =~ ^/.* ]]; then
	SAFE_DEVICE="$DEVICE"
else
	# make everything not starting with / safe for cd-discid, which does not
	# follow the -- convention
	SAFE_DEVICE=./"$DEVICE"
fi

if [[ $# -ge 2 ]]; then
	DIRNAME="$2"
else
	DIRNAME=$(date +%Y%m%d%H%M%S)
fi

mkdir -- "$DIRNAME"
cd -- "$DIRNAME"
tracks=$(cd-discid "$SAFE_DEVICE"|awk '{print $2}')
for track in $(seq -w -- 1 "$tracks"); do
	cdparanoia --force-cdrom-device="$DEVICE" --abort-on-skip --output-wav $track - |
		lame --preset insane - $track.mp3
done
printf '\nCD ripped into %s\n' "$PWD" >&2
