#!/bin/bash

set -Eeu
set -o pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
	printf 'Usage: %q DEVICE [DIRNAME]\n' "$0" >&2
	exit 1
fi

DEVICE="$1"

if [[ $# -ge 2 ]]; then
	DIRNAME="$2"
else
	DIRNAME=$(date +%Y%m%d%H%M%S)
fi

mkdir -- "$DIRNAME"
cd -- "$DIRNAME"
cdda2mp3 dev="$DEVICE" track '--preset insane'
rename -- -track '' *-track.mp3
printf '\nCD ripped into %s\n' "$PWD" >&2
