#!/bin/sh
# periodically print date and load average to the bar

xwrite() {
	file="$1"; shift
	echo -n "$@" | wmiir write "$file"
}

wmiir remove /bar/status 2>/dev/null && sleep 2
wmiir create /bar/status
xwrite /bar/status/colors '#ffffff #000000 #000000'

while xwrite /bar/status/data '[' `cat ~/.ikben` ']' `date '+%A %e %B %Y - %H:%M:%S'`
do
	sleep 1
done
