#!/usr/bin/env bash

set -Eeu -o pipefail

if [[ $# -ne 0 ]]; then
	echo "No arguments please." >&2
	exit 1
fi

cd -- "$(dirname -- "$0")"

# Okay, so, about the state.
# We need to keep the state because it seems to be the only way
# to have the correct NixOS stateVersion, namely the NixOS version
# of the first deploy of the server.
# The rest of the state is not very important (for instance,
# we provision our own SSH keys so we don't need the state for that).
#
# Since I am the only one working on this deployment,
# we can get away with a simple scheme otherwise full of race conditions:
# 1. Try to get the latest state from gently,
#    but don't really mind if this fails, which can easily happen
#    if some services on gently, such as storage, are currently down.
# 2. Do the deploy.
# 3. Copy the state back to gently.

echo "Hi." >&2
echo "I'm a script and I'll be handling your deploy today." >&2
echo "Keep your GPG and SSH passphrases ready." >&2
echo "There we go!" >&2
echo >&2

echo "## Getting state from gently" >&2
if ! scp -- root@gently.radstand.nl:/mnt/storage/live/komputiloj/serviloj-state.nixops "$NIXOPS_STATE"; then
	echo "State could not be retrieved! I will try to use existing local state." >&2
fi

if [[ ! -f "$NIXOPS_STATE" ]]; then
	echo "There is no local state!" >&2
	echo "Did you delete it? Get it back from gently (apparently I wasn't able to, see above)." >&2
	echo "Are you starting over? Then recreate the state, but keep in mind" >&2
	echo "this will potentially pick a different NixOS stateVersion" >&2
	echo "which MIGHT NOT MATCH THE ACTUAL DATE on storage." >&2
	echo "Anyway have fun:" >&2
	printf "%q create serviloj.nix\n" "$NIXOPS_CMD" >&2
	exit 1
fi

echo "## Now deploying. Keep your GPG and SSH passphrases ready." >&2
"$NIXOPS_CMD" deploy

echo "## Pushing new state to gently" >&2
scp -- "$NIXOPS_STATE" root@gently.radstand.nl:/mnt/storage/live/komputiloj/serviloj-state.nixops

