# Note: will be evaluated *on the target machine*
# so keep that in mind when interpreting paths in this file.
{ pkgs, lib, ... }:
{
	# Inspiration taken from https://github.com/nh2/nixops-tutorial/blob/master/example-nginx-deployment.nix

	imports = [ <modules/tilaa_vps.nix> ];

	environment.variables.NIX_PATH = lib.mkForce "/var/src";
	environment.systemPackages = [ pkgs.git ];

	services.openssh.enable = true;
	users.users = {
		root = {
			passwordFile = "/root/password"; # must be present on the machine
			openssh.authorizedKeys.keyFiles = [
				<jeroen_rsa.pub>
			];
		};

		# Make sure users created in the different containers
		# also exist on the machine (actually, in our whole deployment), with a fixed uid.
		# That way files and processes look good both within and outside the container;
		# most importantly files in stokado will have recognizable and consistent owners.
		# Warning: changing uids here after a user has been created has no effect!
		# (I think - the note here was about containers.)
		# You have to rm /var/lib/nixos/uid-map and userdel the user.
		nextcloud = {
			uid = 70000;
		};
	};

	networking = {
		hostName = "gently";
		firewall = {
			allowPing = true;
			# port 80 is only allowed for Let's Encrypt challenges
			allowedTCPPorts = [ 22 80 443 ];
		};
	};

	services.fail2ban.enable = true;

	security.acme = {
		acceptTerms = true;
		# I'm guessing the rest of the cert config is autogenerated
		# due to the nginx config.
		certs."volgendewolk.radstand.nl".email = "jeroen@lwstn.eu";
	};

	services.nginx = {
		enable = true;
		recommendedGzipSettings = true;
		recommendedOptimisation = true;
		recommendedProxySettings = true;
		recommendedTlsSettings = true;

		virtualHosts = {
			"volgendewolk.radstand.nl" = {
				forceSSL = true;
				enableACME = true;
			};
		};
	};

	services.nextcloud = {
		# TODO take relevant php/nextcloud config from current
		# manual installation

		enable = true;

		package = pkgs.nextcloud20;

		home = "/srv/nextcloud";

		autoUpdateApps = {
			enable = true;
		};

		# when it works, we can replace wolk.radstand.nl
		# (also do that above in nginx config)
		hostName = "volgendewolk.radstand.nl";
		https = true; # no idea how this relates to config.overwriteProtocol

		maxUploadSize = "512M";

		config = {
			adminuser = "admin";
			adminpassFile = "/var/src/secrets/admin@nextcloud.password";
			
			dbtype = "sqlite"; # let's start simple
			
			overwriteProtocol = "https";
		};
	};
}
