#!/bin/bash

set -Eeu
set -o pipefail

# We need to record the original PATH for spawning a terminal
# or another program that needs to run with the user's regular PATH:
AMBIENT_PATH="$PATH"
## SPECIFIC FOR RUNNING INSIDE NIX PACKAGE WRAPPER
# But we want to take our dependencies from the DEPS_PATH defined in the package:
export PATH="$DEPS_PATH"
## END SPECIFIC

CMD_AGE=age
CMD_MKPASSWD=mkpasswd
CMD_HTPASSWD=htpasswd # from apache httpd
CMD_COPY="wl-copy --type text/plain --primary"

# Identity to sign with and to always encrypt for:
ME=jeroen@lwstn.eu
AGE_RECIPIENTS=~/passwords/.age/recipients
AGE_IDENTITY=~/passwords/.age/identity.age

try_cloak() {
	if [[ -e "$1" ]]; then
		cloak "$1"
	fi
}

cloak() {
	chmod a= -- "$1"
}

decloak() {
	chmod u=r -- "$1"
}

checkpath() {
	if ! type -P "$1" > /dev/null; then
	 	printf 'Ik vind commando %q niet in $PATH (%q).\n' "$1" "$PATH" >&2
		return 1
	fi
}

checkpath $CMD_AGE
checkpath $CMD_MKPASSWD
checkpath $CMD_HTPASSWD

# from coreutils:
checkpath tr
checkpath head
checkpath mkdir
checkpath chmod

main() {
	local command
	if test $# -eq 0; then
		command=""
	else
		command="$1"
		shift
	fi

	case "$command" in
	get-exact)
		# get-exact is a bit of a misnomer: it will not show the exact password
		# all it did was not append a newline
		printf '`%q get-exact` is deprecated; use `%q cat -n` instead.\n' "$0" "$0" >&2
		do_show plain -n -- "$@"
	;;
	show|cat)
		do_show plain "$@"
	;;
	copy)
		do_copy "$@"
	;;
	hash)
		# output passwords in /etc/shadow-like format
		do_show hashed "$@"
	;;
	hash-with-bcrypt)
		do_show hashed_bcrypt "$@"
	;;
	add|new)
		set -o noclobber

		file="$1"
		shift
		if [ -e "$file" ]; then
		  echo "Wachtwoord $file bestaat al." >&2
		  exit 1
		fi
		
		# local recipients=(--recipient "$ME")
		for recipient in "$@"; do
			echo "Extra ontvangers zijn niet ondersteund." >&2
			exit 1
			# echo "Wachtwoord zal ook leesbaar zijn voor $recipient" >&2
			# recipients+=(--recipient "$recipient")
		done
		
		local pass=""
		if tty -s; then
			# If terminal; ask for a one line password
			stty -echo
			read -r -p "Wachtwoord: " pass
			stty echo
		else
			# Otherwise, read full input
			pass=$(cat)
		fi
		if [ -z "$pass" ]; then
			echo "Geen wachtwoord gegeven." >&2
			exit 1
		fi
		local content
		# We don't redirect the command to $file directly so no empty file will be created on error
		content=$(printf "%s" "$pass" | $CMD_AGE --encrypt --armor --recipients-file="$AGE_RECIPIENTS")
		printf "%s" "$content" > "$file"
		echo "Wachtwoord $file opgeslagen." >&2
	;;
	session)
		WACHTWOORD_SESSION_ID="$(random_string 64)"
		do_unlock
		export WACHTWOORD_SESSION_ID
		export PATH="$AMBIENT_PATH"
		if [[ $# -eq 0 ]]; then
			"$SHELL"
		else
			"$@"
		fi
		do_lock
	;;
	# manual sessions for other tools, not for the user
	manual-session-unlock)
		do_unlock
	;;
	manual-session-lock)
		do_lock
	;;
	cleanup-sessions)
		# The makes the directory listable,
		# that's why we bother with all the cloaking:
		# the files will not be readable themselves
		# in the small window of time between chmod and rm.
		chmod u=rwx -- "$XDG_RUNTIME_DIR"/wachtwoord
		rm -rf -- "$XDG_RUNTIME_DIR"/wachtwoord
		unset WACHTWOORD_SESSION_ID
	;;
	*)
		echo "Onbekend commando '$command'. Tot ziens!" >&2
		exit 1
	;;
	esac
}

do_copy() {
	if [[ $# -gt 1 ]]; then
		printf 'Please specify at most one password file.\n' >&2
	fi
	do_show plain -n "$@" | $CMD_COPY
}

do_show() {
	local method="$1"
	shift
	local success=0
	local seen=0
	local prefix=""
	local content
	local suppress_last_newline=no
	local format
	local cmd
	while [ $# -ge 1 ]; do
		case "$1" in
		-n)
			suppress_last_newline=yes
			shift
		;;
		--)
			shift
			break
		;;
		-*)
			echo "Unrecognized option: $1" >&2
			exit 1
		;;
		*)
			break
		;;
		esac
	done
	if [ $# -eq 0 ]; then
		echo "Reading from stdin..." >&2
		set -- -
	fi
	if [ $# -gt 1 ]; then
		format=multi
	else
		format=single
	fi
	if [[ -v WACHTWOORD_SESSION_ID && -n "$WACHTWOORD_SESSION_ID" ]]; then
		AGE_IDENTITY="$XDG_RUNTIME_DIR"/wachtwoord/"$WACHTWOORD_SESSION_ID"
		if [[ -e "$AGE_IDENTITY" ]]; then
			decloak "$AGE_IDENTITY"
			trap 'try_cloak "$AGE_IDENTITY"' EXIT
		fi
	fi
	for file in "$@"; do
		# We let age produce any errors for us and use && to make sure we continue with the other files in case of an error
		content=$($CMD_AGE --decrypt --identity="$AGE_IDENTITY" -- "$file") && {
			if [ $success -gt 0 ]; then
				# This approach gives a messy combination of stdout and stderr,
				# but it does make sure we never put empty lines on stdout.
				printf '\n'
			fi
			if [ $format = multi ]; then
				printf '%s:' "$file"
			fi
			show_"$method" "$content"
			let ++success # ++ first because of weird exit code if expression is 0
		}
	done
	if [[ -v WACHTWOORD_SESSION_ID && -n "$WACHTWOORD_SESSION_ID" && -e "$AGE_IDENTITY" ]]; then
		cloak "$AGE_IDENTITY"
	fi
	if [ "$suppress_last_newline" = no -a $success -gt 0 ]; then
		printf '\n'
	fi
	if [ $success -lt $# ]; then
		exit 1
	fi
}

show_plain() {
	printf "%s" "$1"
}
show_hashed() {
	printf '%s' "$1" | $CMD_MKPASSWD --stdin --method=sha512crypt | tr -d %'\n'
}
show_hashed_bcrypt() {
	# bcrypt is more robust against offline brute-forcing,
	# but does not seem to be supported for use in /etc/shadow
	printf '%s' "$1" | $CMD_HTPASSWD -niB username | cut -d: -f2 | tr -d $'\n'
}

do_unlock() {
	local decrypted
	mkdir -p -- "$XDG_RUNTIME_DIR"/wachtwoord
	chmod a=,u=wx -- "$XDG_RUNTIME_DIR"/wachtwoord
	decrypted=$($CMD_AGE --decrypt -- "$AGE_IDENTITY")
	printf '%s' "$decrypted" > "$XDG_RUNTIME_DIR"/wachtwoord/"$WACHTWOORD_SESSION_ID"
	cloak "$XDG_RUNTIME_DIR"/wachtwoord/"$WACHTWOORD_SESSION_ID"
}

do_lock() {
	rm -f -- "$XDG_RUNTIME_DIR"/wachtwoord/"$WACHTWOORD_SESSION_ID"
	unset WACHTWOORD_SESSION_ID
}

random_string() {
	local length
	length="$1"
	# https://stackoverflow.com/a/66223024/21375902
	head -c "$length" <(tr -dc 'a-zA-Z0-9' < /dev/urandom)
}

main "$@"
