#!/usr/bin/env bash

set -Eeu -o pipefail

channel_url=$(cat channel_url)
current_overview_url=$(curl --head --silent --write-out "%{redirect_url}\n" --output /dev/null "$channel_url")
if [[ -z "$current_overview_url" ]]; then
	echo "Could not determine current url for channel $channel_url" >&2
	echo "Likely cause: a typo in the channel name." >&2
	echo "Less likely cause: a change in nixos.org redirect structure." >&2
	exit 2
fi
current_url="$current_overview_url"/nixexprs.tar.xz
current_sha=$(nix-prefetch-url --unpack "$current_url")
# printf "%s" "$current_url" > current_url
# printf "%s" "$current_sha" > current_sha
cat > default.nix <<-EOF
	# GENERATED
	with builtins;
	rec {
	    nix_path = fetchTarball {
	        url    = "$current_url";
	        sha256 = "$current_sha";
	    };
	    value = import nix_path;
	}
EOF
