#!/usr/bin/env bash

set -Eeu -o pipefail

# NOTE: the testapi url as specified on https://www.versio.nl/RESTapidoc/ gives a 404.
# api_base=https://www2.versio.nl/testapi/v1
api_base=https://www2.versio.nl/api/v1

domain=$(basename -- "$PWD")

payload=$(cat -- ./records | \
	# remove comment lines:
	grep -Ev '^;' | \
 	# remove empty lines:
 	grep -Ev '^[[:space:]]*$' | \
 	# make jsons:
 	jq -Rc 'split("\t+"; "") | { name: .[0], ttl: .[1] | tonumber, type: .[3],
		value: (.[4] | sub("^[0-9]+ +"; "")),
		prio: (.[4] | [scan("^[0-9]+ ")][0] // "0" | tonumber) }' | \
 	# join json:
 	jq --slurp -c '{dns_records: .}')

# curl -X GET \
# 	-H "Content-Type: application/json" \
# 	--config <(
# 		printf -- '--user "%s"\n' "$VERSIO_USER"
# 	) \
# 	--fail \
# 	"$api_base"/domains/"$domain"'?show_dns_records=true'
# echo

curl -X POST \
	-H "Content-Type: application/json" \
	--config <(
		printf -- '--user "%s"\n' "$VERSIO_USER"
	) \
	--fail \
	-d "$payload" \
	"$api_base"/domains/"$domain"/update
echo

printf "%s OK :)\n" "$domain"
