#!/bin/sh
# configure wmii

xwrite() {
	file="$1"; shift
	echo -n "$@" | wmiir write "$file"
}

proglist() {
	ls -lL "$@" 2>/dev/null | awk 'NF>2 && $1 ~ /^[^d].*x/ {print $NF}' | sort -u
}

volgende() {
  curtag=`wmiir read /view/name`
  echo $@ $@|awk "{for(x=1;x<=NF;x++)if(\$x~\"$curtag\"){print \$(x+1); break}}"
}

next_tag() {
  volgende `wmiir read /tags|xargs`
}

prev_tag() {
  volgende `wmiir read /tags|tac|xargs`
}



MODKEY=Mod4
#MODKEY=Multi_key #kapot!
UP=Up
DOWN=Down
LEFT=Left
RIGHT=Right

WMII_FONT='fixed'
#WMII_SELCOLORS='#ffffff #285577 #4c7899'
#WMII_NORMCOLORS='#222222 #eeeeee #666666'

WMII_SELCOLORS='#ffffff #650e59 #420832'
WMII_NORMCOLORS='#aaaaaa #000000 #444444'

#kies een willekeurige wallpaper

if [ -e ~/wallpapers ]; then
  display -window root -resize 1280x1024 -backdrop `~/bin/kiesmaar ~/wallpapers/*`
fi

# dark background
#WMII_NORMCOLORS='#e0e0e0 #0a0a0a #202020'

export WMII_FONT WMII_NORMCOLORS WMII_SELCOLORS

# give wmiiwm a chance to start
while :
do
	echo Start wmiirc | wmiir write /event >/dev/null 2>&1 && break
	sleep 1
done

# WM CONFIGURATION
xwrite /def/border 2
xwrite /def/font $WMII_FONT
xwrite /def/selcolors $WMII_SELCOLORS
xwrite /def/normcolors $WMII_NORMCOLORS
xwrite /def/colmode default
xwrite /def/colwidth 0

# TAGGING RULES
wmiir write /def/rules <<EOF
/.*eclipse.*/ -> 5
/gaim.*/ -> 1
/rhythmbox.*/ -> 9
/Firefox.*/ -> 3
/.*thunderbird.*/ -> 4
/totem.*/ -> ~
/XMMS.*/ -> ~
/Gimp.*/ -> ~
/MPlayer.*/ -> ~
/.*/ -> !
/.*/ -> 1
EOF

xwrite /

# MISC
#xsetroot -solid '#333333'
status &
PROGS_FILE=`mktemp /tmp/.wmiimenu.proglist.XXXXXX` || exit 2
proglist `echo "$OLD_PATH" | tr : ' '` >$PROGS_FILE &

# SHORTCUTS
xwrite /def/grabmod Mod1
wmiir write /def/keys <<EOF
$MODKEY-$LEFT
$MODKEY-$RIGHT
$MODKEY-$DOWN
$MODKEY-$UP
$MODKEY-space
$MODKEY-comma
$MODKEY-f
$MODKEY-period
$MODKEY-slash
$MODKEY-Home
$MODKEY-End
$MODKEY-Insert
$MODKEY-0
$MODKEY-1
$MODKEY-2
$MODKEY-3
$MODKEY-4
$MODKEY-5
$MODKEY-6
$MODKEY-7
$MODKEY-8
$MODKEY-9
$MODKEY-KP_0
$MODKEY-KP_1
$MODKEY-KP_2
$MODKEY-KP_3
$MODKEY-KP_4
$MODKEY-KP_5
$MODKEY-KP_6
$MODKEY-KP_7
$MODKEY-KP_8
$MODKEY-KP_9
$MODKEY-Return
$MODKEY-Shift-$LEFT
$MODKEY-Shift-$RIGHT
$MODKEY-Shift-$UP
$MODKEY-Shift-$DOWN
$MODKEY-Shift-space
$MODKEY-Delete
$MODKEY-Shift-Insert
$MODKEY-Shift-KP_0
$MODKEY-Shift-KP_1
$MODKEY-Shift-KP_2
$MODKEY-Shift-KP_3
$MODKEY-Shift-KP_4
$MODKEY-Shift-KP_5
$MODKEY-Shift-KP_6
$MODKEY-Shift-KP_7
$MODKEY-Shift-KP_8
$MODKEY-Shift-KP_9
$MODKEY-Shift-0
$MODKEY-Shift-1
$MODKEY-Shift-2
$MODKEY-Shift-3
$MODKEY-Shift-4
$MODKEY-Shift-5
$MODKEY-Shift-6
$MODKEY-Shift-7
$MODKEY-Shift-8
$MODKEY-Shift-9
$MODKEY-Control-$LEFT
$MODKEY-Control-$RIGHT
$MODKEY-Control-$DOWN
$MODKEY-Control-$UP
XF86AudioLowerVolume
XF86AudioRaiseVolume
XF86AudioMute
$MODKEY-Tab
$MODKEY-Shift-Tab
$MODKEY-Control-Shift-$LEFT
$MODKEY-Control-Shift-$RIGHT
$MODKEY-Scroll_Lock
EOF

# EVENT LOOP
wmiir read /event 2>/dev/null |
while read event
do
	set -f
	set -- $event
	set +f
	type="$1"; shift
	case "$type" in
	Start)
		if test wmiirc = "$1"
		then
			rm -f $PROGS_FILE
			exit
		fi;;
	BarClick)
	  case "$2" in
	    1)
		    xwrite /ctl view "$1";;
#		  3)
#		    xwrite /view/sel/sel/tags "$1";;
		  4)
		    xwrite /ctl view `next_tag`;;
		  5)
		    xwrite /ctl view `prev_tag`;;
	  esac;;
	Key)
		case "$1" in
		$MODKEY-$LEFT)
			xwrite /view/ctl select prev;;
		$MODKEY-$RIGHT)
			xwrite /view/ctl select next;;
		$MODKEY-$DOWN)
			xwrite /view/sel/ctl select next;;
		$MODKEY-$UP)
			xwrite /view/sel/ctl select prev;;
		$MODKEY-space)
			xwrite /view/ctl select toggle;;
		$MODKEY-comma)
			xwrite /view/sel/mode default;;
		$MODKEY-period)
			xwrite /view/sel/mode stack;;
		$MODKEY-slash)
			xwrite /view/sel/mode max;;
		$MODKEY-f)
			xwrite /view/0/sel/geom 0 0 east south;;
		$MODKEY-Home)
			`proglist $HOME/.wmii-3 | wmiimenu` &;;
		$MODKEY-End)
			PATH="$OLD_PATH" wmiisetsid `wmiimenu <$PROGS_FILE` &;;
		$MODKEY-Insert)
			xwrite /ctl view "`wmiir read /tags | wmiimenu`" &;;
		$MODKEY-KP_[0-9] )
			xwrite /ctl view `echo $1 | sed 's/.*_//'`;;
		$MODKEY-[0-9] )
			xwrite /ctl view `echo $1 | sed 's/.*-//'`;;
		$MODKEY-Return)
			PATH="$OLD_PATH" x-terminal-emulator &;;
		$MODKEY-Shift-$LEFT)
			xwrite /view/sel/sel/ctl sendto prev;;
		$MODKEY-Shift-$RIGHT)
			xwrite /view/sel/sel/ctl sendto next;;
		$MODKEY-Shift-$DOWN)
			xwrite /view/sel/sel/ctl swap down;;
		$MODKEY-Shift-$UP)
			xwrite /view/sel/sel/ctl swap up;;
		$MODKEY-Shift-space)
			xwrite /view/sel/sel/ctl sendto toggle;;
		$MODKEY-Delete)
			xwrite /view/sel/sel/ctl kill;;
		$MODKEY-Shift-Insert)
			xwrite /view/sel/sel/tags "`wmiir read /tags | wmiimenu`" &;;
		$MODKEY-Shift-KP_[0-9] )
			xwrite /view/sel/sel/tags `echo $1 | sed 's/.*_//'`;;
		$MODKEY-Shift-[0-9] )
			xwrite /view/sel/sel/tags `echo $1 | sed 's/.*Shift-//'`;;
		$MODKEY-Control-$LEFT)
			xwrite /view/sel/sel/ctl swap prev;;
		$MODKEY-Control-$RIGHT)
			xwrite /view/sel/sel/ctl swap next;;
		$MODKEY-Control-$DOWN)
			xwrite /view/sel/sel/ctl swap down;;
		$MODKEY-Control-$UP)
			xwrite /view/sel/sel/ctl swap up;;
	  XF86AudioMute )
	    amixer set PCM toggle;;
	  XF86AudioRaiseVolume )
	    amixer set PCM 5%+;;
	  XF86AudioLowerVolume )
	    amixer set PCM 5%-;;

	  $MODKEY-Scroll_Lock )
	    lock;;
	  
    $MODKEY-Tab )
      xwrite /ctl view `next_tag`;;
    $MODKEY-Shift-Tab )
      xwrite /ctl view `prev_tag`;;


	  #werkt niet:
    $MODKEY-Control-Shift-$RIGHT) # column width incr
      xwrite /view/sel/sel/geom +0 +0 +24 +0;;
    $MODKEY-Control-Shift-$LEFT) # column width decr
      xwrite /view/sel/sel/geom +0 +0 -24 +0;;
    esac;;
	esac
done &

#zorg voor goede gnome-thema
gnome-settings-daemon > /dev/null &

