#!/bin/bash

set -Eeu
set -o pipefail

set -o noclobber

RADICALE_USER="$1"

cd collection-root
for dir in *; do
(
	cd -- "$dir"
	if [ -d .git ]; then
		git config user.name radicale
		git config user.email radicale@radstand.nl
		git add -A
		git diff --cached --quiet || git commit -m "Changes by $RADICALE_USER"
		git push
		# Sendmail coredumps??? Also, we don't want to send everyone's agenda changes to one person.
		# git log -1 HEAD -p | mail -aFrom:radicale@radstand.nl -s '[agenda] Wijziging! 🥔' jeroen@lwstn.eu
	fi
)
done
